team_selection_task:
  name: team_selection_task
  description: >
    You are responsible for analyzing the project {project_name} and selecting the appropriate team members to execute the development efficiently.

    Instructions
    ------------
    - Carefully analyze the project requirements write by the user, it might not be a technical person so you must handle some possible mistakes.
    - Identify the necessary roles (e.g., Software Architect, Frontend Developer, Backend Developer, Aggregator).
    - Assign tasks to the right agents based on their expertise.
    - Never use more resoursces (agents) than necessary, always try to use the minimum number of agents to do the job, without affect the quality.
    - Ensure that dependencies are respected (e.g., Software Architect must define architecture before development starts, and Technical Writter must write after the doders finish their part).
    - You must follow the given example here, (inplace of <Left brace> use curly bracket opened to right and <Right brace> use curly bracket opened to left):
     <Left brace>
      agents_tasks: 
        <Left brace>
          agent: task
        <Right brace>,
        <Left brace>
          agent: task
        <Right brace>,
    <Right brace>
    - The output must be a JSON (python dictionary) object with the following structure, one dictionary with one key called agents_tasks and the value must be another dictionary with the agents as key and their tasks as values.
    - Always add the code_aggregator_agent and his task code_aggregation_task in the end of the staff, this agent is repponsible for organise everything for the final user.

    Agents available for assignment:
    {agents_tasks}

    Project Description:
    {project_description}

  expected_output: >
    The result must be a simple JSON object with all necessary agenst and their tasks, only this structure and nothing else.
  agent: team_selector_agent
